name: Count Lines of md
on: [pull_request]

jobs:
  count-lines:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout ğŸ›ï¸
        uses: actions/checkout@v3


      - name: Count Lines of md ğŸ“Š
        run: |
          # íƒìƒ‰í•  ë””ë ‰í„°ë¦¬ ì„¤ì •, ê¸°ë³¸ê°’ì€ í˜„ì¬ ë””ë ‰í„°ë¦¬
          DIRECTORY=${1:-.}

          # .md íŒŒì¼ ì°¾ê¸° ë° ì¤„ ìˆ˜ ê³„ì‚°
          find "$DIRECTORY" -type f -name "*.md" | while read -r file; do
            line_count=$(wc -l < "$file")
            if [ "$line_count" -le 10 ]; then
              echo "Error: File '$file' has 10 lines or less ($line_count lines)." >&2
              exit 1
            fi
          done

          echo "All .md files have more than 10 lines."